language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g jasmine-node
branches:
  only:
  - bramble
deploy:
  provider: s3
  access_key_id: AKIAJZZYAKJA33TQEHLA
  secret_access_key:
    secure: PUmptcr3naHfuC1FU8q7F3OEbnbCzfKaTYleJDpYjz7lSt24zoXD5epaTcusva4SafMS3I5NeKZ79YmDrn2ONEyLdyPCLKNScOFEClhjFNeuMOrf63fK3MO1RwNtJ2Rvjwwi2k+/pVaVUXKcr287JWywDZUZfYp7DjxJdNU6JZ0=
  bucket: mozillathimblelivepreview.net
  local-dir: dist
  upload-dir: bramble/dist
  skip_cleanup: true
  on:
    repo: humphd/brackets
    branch: bramble
