language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt-cli
  - npm install -g jasmine-node
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9c767842144fd24d26a5
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
