language: node_js
sudo: false # use container-based Travis infrastructure
node_js:
  - "6"
before_script:
- npm install -g grunt-cli
script: grunt build-browser-compressed
branches:
  only:
  - master
  - production
notifications:
  irc: "irc.mozilla.org#thimble"
env:
  global:
    - secure: OvDWteGJ/ctOzXudDb8icaLCtdJTd1HbQq5T9HvS7ZF8IDs6xM+atqxYWeyC+2sm7fLNkWjndcKrXFqZ3TRltW7ibaKreUMtUVaVKc7mGBNBn/gVfCNvHRlbDYr6bMUVapk9x1Ql6p2jE/Ss+p2EEGkzvHPKn2RMRWOQQQM7wTQ=
  matrix:
    - AWS_ACCESS_KEY_ID=AKIAI7XHSZFYVHFRTRIA CLOUDFRONT_DISTRIBUTION_ID=ENS8DUD0WOHD9
deploy:
  - provider: s3
    access_key_id: AKIAI7XHSZFYVHFRTRIA
    secret_access_key:
      secure: XFKkzJRsjVXShcDrTdihLug1CZjr3s/2rSpQrzQnkl2ChM+waydLqd8jHrfkIUl6np2pxO8JU3HWe9AYfuTMdNhWijQS2E1xesUTTK9KQaPdu5mhe98AkCu/rziAv485To4hze0om8GHyREUR1cOxalYVflupZtHIkKzQgbF8AY=
    bucket: mozillathimblelivepreview-net-s3bucket-l1armm3pssk5
    local-dir: dist
    upload-dir: bramble/staging/dist
    skip_cleanup: true
    detect_encoding: true
    on:
      repo: mozilla/brackets
      branch: master
      condition: $UPDATE_STRINGS != true
  - provider: s3
    access_key_id: AKIAI7XHSZFYVHFRTRIA
    secret_access_key:
      secure: XFKkzJRsjVXShcDrTdihLug1CZjr3s/2rSpQrzQnkl2ChM+waydLqd8jHrfkIUl6np2pxO8JU3HWe9AYfuTMdNhWijQS2E1xesUTTK9KQaPdu5mhe98AkCu/rziAv485To4hze0om8GHyREUR1cOxalYVflupZtHIkKzQgbF8AY=
    bucket: mozillathimblelivepreview-net-s3bucket-l1armm3pssk5
    local-dir: dist
    upload-dir: bramble/production/dist
    skip_cleanup: true
    detect_encoding: true
    on:
      repo: mozilla/brackets
      branch: production
      condition: $UPDATE_STRINGS != true
after_deploy:
- node invalidate.js
