language: node_js
node_js:
- '0.10'
sudo: false
before_script:
- npm install -g grunt-cli
- npm install -g jasmine-node
branches:
  only:
  - bramble
  - production
notifications:
  irc: "irc.mozilla.org#thimble"
deploy:
  - provider: s3
    access_key_id: AKIAI7XHSZFYVHFRTRIA
    secret_access_key:
      secure: XFKkzJRsjVXShcDrTdihLug1CZjr3s/2rSpQrzQnkl2ChM+waydLqd8jHrfkIUl6np2pxO8JU3HWe9AYfuTMdNhWijQS2E1xesUTTK9KQaPdu5mhe98AkCu/rziAv485To4hze0om8GHyREUR1cOxalYVflupZtHIkKzQgbF8AY=
    bucket: mozillathimblelivepreview-net-s3bucket-l1armm3pssk5
    local-dir: dist
    upload-dir: bramble/staging/dist
    skip_cleanup: true
    detect_encoding: true
    on:
      repo: humphd/brackets
      branch: bramble
  - provider: s3
    access_key_id: AKIAI7XHSZFYVHFRTRIA
    secret_access_key:
      secure: XFKkzJRsjVXShcDrTdihLug1CZjr3s/2rSpQrzQnkl2ChM+waydLqd8jHrfkIUl6np2pxO8JU3HWe9AYfuTMdNhWijQS2E1xesUTTK9KQaPdu5mhe98AkCu/rziAv485To4hze0om8GHyREUR1cOxalYVflupZtHIkKzQgbF8AY=
    bucket: mozillathimblelivepreview-net-s3bucket-l1armm3pssk5
    local-dir: dist
    upload-dir: bramble/production/dist
    skip_cleanup: true
    detect_encoding: true
    on:
      repo: humphd/brackets
      branch: production
